export const STORAGE_KEYS = {
  skipBootAnimation: 'shittim.settings.skipBootAnimation',
  skipBootOnce: 'shittim.settings.skipBootOnce',
  keepAwake: 'shittim.settings.keepAwake',
  tasks: 'shittim.tasks.v1',
  iconPositions: 'shittim.home.iconPositions.v1',
  scheduleEvents: 'shittim.schedule.events.v1',
  galleryPhotos: 'shittim.gallery.photos.v1',
  quizStats: 'shittim.quiz.stats.v1',
  fullRoundBest: 'shittim.quiz.fullRoundBest.v1',
  ownedCharacters: 'shittim.students.owned.v1',
  dutyStudent: 'shittim.students.duty.v1',
  systemErrorActive: 'shittim.system.errorActive.v1',
  language: 'shittim.settings.language',
} as const;
